/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WinGameImport } from './routes/winGame'
import { Route as TutorialImport } from './routes/tutorial'
import { Route as SupportImport } from './routes/support'
import { Route as SettingsImport } from './routes/settings'
import { Route as SelectLevelImport } from './routes/selectLevel'
import { Route as MenuImport } from './routes/menu'
import { Route as LoseGameImport } from './routes/loseGame'
import { Route as GameImport } from './routes/game'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WinGameRoute = WinGameImport.update({
  path: '/winGame',
  getParentRoute: () => rootRoute,
} as any)

const TutorialRoute = TutorialImport.update({
  path: '/tutorial',
  getParentRoute: () => rootRoute,
} as any)

const SupportRoute = SupportImport.update({
  path: '/support',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRoute = SettingsImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const SelectLevelRoute = SelectLevelImport.update({
  path: '/selectLevel',
  getParentRoute: () => rootRoute,
} as any)

const MenuRoute = MenuImport.update({
  path: '/menu',
  getParentRoute: () => rootRoute,
} as any)

const LoseGameRoute = LoseGameImport.update({
  path: '/loseGame',
  getParentRoute: () => rootRoute,
} as any)

const GameRoute = GameImport.update({
  path: '/game',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameImport
      parentRoute: typeof rootRoute
    }
    '/loseGame': {
      id: '/loseGame'
      path: '/loseGame'
      fullPath: '/loseGame'
      preLoaderRoute: typeof LoseGameImport
      parentRoute: typeof rootRoute
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuImport
      parentRoute: typeof rootRoute
    }
    '/selectLevel': {
      id: '/selectLevel'
      path: '/selectLevel'
      fullPath: '/selectLevel'
      preLoaderRoute: typeof SelectLevelImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportImport
      parentRoute: typeof rootRoute
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialImport
      parentRoute: typeof rootRoute
    }
    '/winGame': {
      id: '/winGame'
      path: '/winGame'
      fullPath: '/winGame'
      preLoaderRoute: typeof WinGameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  GameRoute,
  LoseGameRoute,
  MenuRoute,
  SelectLevelRoute,
  SettingsRoute,
  SupportRoute,
  TutorialRoute,
  WinGameRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/game",
        "/loseGame",
        "/menu",
        "/selectLevel",
        "/settings",
        "/support",
        "/tutorial",
        "/winGame"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/game": {
      "filePath": "game.tsx"
    },
    "/loseGame": {
      "filePath": "loseGame.tsx"
    },
    "/menu": {
      "filePath": "menu.tsx"
    },
    "/selectLevel": {
      "filePath": "selectLevel.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/support": {
      "filePath": "support.tsx"
    },
    "/tutorial": {
      "filePath": "tutorial.tsx"
    },
    "/winGame": {
      "filePath": "winGame.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
